### ISSUE TITLE
Selección del destino para el envío del SII

### ISSUE THREAD

**Issue by fandujar71** [mdiago/EasySII#4]
Como podría añadir en la aplicación una ventana que me pida que elija si lo envío a Producción o a Preproducción, porque actualmente estamos cambiando el fichero EasySII.xml, para que unas veces apunte a Pre y otras a Pro. Tengo dos ficheros uno con cada sistema y los voy renombrando a este, pero nos gustaría que nos preguntara antes y no tener que estar renombrando los ficheros.
Quizá se podría que según el destino se llame a un fichero o a otro, sin necesidad de renombrarlos.

Saludos.

**Comment by mdiago** [comment]
### Cambiar el archivo de configuración o trabajar con varias configuraciones

Podemos trabajar con varios archivos de configuración para alternar entre la configuración de pruebas y producción; para gestionar un entorno mutltiempresa con distintos certificados...

```C#
          
         // Archivo de pruebas que quiero utilizar.
            string configFilePruebas = "pruebas.xml";

            // Establezco el nombre del archivo de configuración a utilizar,
            // ahora estoy trabajando con las opciones de pruebas.
            EasySII.Settings.SetConfigFileName(configFilePruebas);


            // Las modifico como quiero.
            EasySII.Settings.Current.IDVersionSii = "1.0"; // versión del SII a utilizar en la serialización xml
            EasySII.Settings.Current.InboxPath = @"C:\ProgramData\EasySII\pruebas\inbox"; // almacén respuestas pruebas
            EasySII.Settings.Current.OutboxPath = @"C:\ProgramData\EasySII\pruebas\outbox"; // almacén envíos pruebas
            EasySII.Settings.Current.SiiEndPointPrefix = SiiEndPointPrefixes.Test; // EndPoint pruebas

            // guardo las modificaciones si procede
            EasySII.Settings.Save();

            // Archivo de producción que quiero utilizar.
            string configFileProduccion = "produccion.xml";

            // Establezco el nombre del archivo de configuración a utilizar,
            // ahora estoy trabajando con las opciones de producción.
            EasySII.Settings.SetConfigFileName(configFileProduccion);


            // Las modifico como quiero.
            EasySII.Settings.Current.IDVersionSii = "1.1"; // versión del SII a utilizar en la serialización xml
            EasySII.Settings.Current.InboxPath = @"C:\ProgramData\EasySII\produccion\inbox"; // almacén respuestas producción
            EasySII.Settings.Current.OutboxPath = @"C:\ProgramData\EasySII\produccion\outbox"; // almacén envíos producción
            EasySII.Settings.Current.SiiEndPointPrefix = SiiEndPointPrefixes.Prod; // EndPoint producción

            // guardo las modificaciones si procede
            EasySII.Settings.Save();

```

**Comment by fandujar71** [comment]
Lo que quería hacer, es que antes de ejecutar el programa de transferencia, me apareciera una ventana donde debo elegir si quiero enviarlo al entorno de Productivo o de Preproductivo, y en función de la elección debería cargar el fichero EasySII_DES.xml o EasySII_PRO.xml.

**Comment by mdiago** [comment]
Se trata de una aplicación de consola, windows forms, wpf?

**Comment by mdiago** [comment]
Por ejemplo en una aplicación windows forms:

```C#
          

            // Pregunto si quiero entrar en productivo.
       var respuesta = MessageBox.Show("¿Desea entrar en modo producción?\n" +
                "Si hace click en NO entrará en modo test.", 
                "SELECCIÓN MODO PRODUCCIÓN-TEST", MessageBoxButtons.YesNo, 
                    MessageBoxIcon.Question);

            if (respuesta == DialogResult.Yes)
            {
                // Selecciono el fichero de configuración del entorno de producción
                EasySII.Settings.SetConfigFileName("EasySII_PRO.xml");
            }
            else
            {
                // Selecciono el fichero de configuración del entorno de pruebas
                EasySII.Settings.SetConfigFileName("EasySII_DES.xml");
            }

```

**Comment by mdiago** [comment]
Por ejemplo en una aplicación de consola:

```C#
          

            // Pregunto si quiero entrar en productivo.
    Console.WriteLine("Seleccione entorno P=producción / T=test.");

            string respuesta = Console.ReadLine().ToUpper();

            if (respuesta == "P")
            {
                // Selecciono el fichero de configuración del entorno de producción
                EasySII.Settings.SetConfigFileName("EasySII_PRO.xml");
            }
            else if (respuesta == "T")
            {
                // Selecciono el fichero de configuración del entorno de pruebas
                EasySII.Settings.SetConfigFileName("EasySII_DES.xml");
            }
            else
            {
                throw new ArgumentException($"Valor {respuesta} no permitido. " +
                    "Sólo válidos los valores 'T' y 'P'"); 
            }
           
```

**Comment by fandujar71** [comment]
Manuel, una consulta, luego si quieres la meto en el portal para que la
contestes.

He creado una form, que en funición de si el programa se ejecuta desde
dentro de CAC o desde fuera, tiene que configurar la conexión de manera
diferente.



En función de lo elegido quería crear una Variable global que se llamara
sistema_destino, y que me permitiera elegir el sistema destino y desde
donde se llama.
Luego en la configuración de SAP he creado las cuatro configuraciones
diferentes, pero no soy capaz de pasarle a la función de Login esa variable.





namespace SiiBlumaqES
{
    class SAPConecta
    {
        public static RfcDestination Login()
        {
            try
            {
                RfcDestinationManager.RegisterDestinationConfiguration(new
SAPConfig());
            }
            catch
            {
            }

            //RfcDestination SapRfcDestination =
RfcDestinationManager.GetDestination("DES");
            RfcDestination SapRfcDestination =
RfcDestinationManager.GetDestination(Program.sistema_destino);   <-- Aquí
me da error porque no puede acceder a la variable global.
            return SapRfcDestination;
        }
    }
}


No sé si me puedes echar una mano, para ver como le puedo pasar esa
variable global, al  RfcDestination SapRfcDestination =
RfcDestinationManager.GetDestination(Variable Global);
Esto lo he pensado por no tener que tocar todas las llamadas a las
funciones de conexiónd de SAP pasándole como parametro el destino, pero a
lo mejor estoy yendo por mal camino.

Gracias y disculpa las molestias.

Saludos.




El 26 de junio de 2018, 12:47, Manuel Diago Garcia <notifications@github.com

**Comment by mdiago** [comment]
¿ Me puedo conectar mediante TeamViewer a tu equipo y lo vemos ?

**Comment by fandujar71** [comment]
Manuel, pues ahora es imposible, porque tengo que solicitar una VPN y ya me
han dicho que hoy imposible.



El 27 de junio de 2018, 13:08, Manuel Diago Garcia <notifications@github.com

**Comment by mdiago** [comment]
Crea una clase como está:

   /// <summary>
    /// Almacena las variables globales del sistema.
    /// </summary>
    public class ParametrosGlobales
    {

        /// <summary>
        /// Sistema destino RFC SAP.
        /// </summary>
        public static string SapRfcSistemaDestino { get; set; }

        /// <summary>
        /// Constructor estático: sólo se ejecuta una vez.
        /// </summary>
        static ParametrosGlobales()
        {
            SapRfcSistemaDestino = "MiSistemaDestino";
        }
    }



Luego en tu programa:


            // Así accederás al valor
            var test = ParametrosGlobales.SapRfcSistemaDestino;

            // Así cambiarás el valor
            ParametrosGlobales.SapRfcSistemaDestino =
"MiNuevoSistemaDestino";

**Comment by fandujar71** [comment]
Manuel, perfecto, me ha funcionado perfectamente.

He solicitado una VPN para ti, por si alguna vez te quieres conectar.
Cuando me la pasen ya te pasaré todos los datos.

Saludos.


El 27 de junio de 2018, 13:19, Manuel Diago Garcia <notifications@github.com

**Comment by mdiago** [comment]
👍
