### ISSUE TITLE
Problemas en selección alternativa del entorno de Preproducción y producción.

### ISSUE THREAD

**Issue by fandujar71** [mdiago/EasySII#5]
Hemos realizado una adaptación del programa de envío del SII, para poder seleccionar el entorno al que queremos enviar, porque a veces nos interesa hacer pruebas en el entorno de Preproducción y posteriormente enviarlas a Producción.
Para ello hemos creado dos ficheros de configuración, uno que apunta al entorno de Preproducción (EasySII_DES.xml) y el otro a Producción (EasySII_PRO.xml). De esta forma hemos dejado de utilizar el fichero que utilizaba por defecto (EasySII.xml).
El problema que nos hemos encontrado, es que a pesar que lee correctamente el fichero de configuración al que tiene que ir dirigido, por algún motivo no actualiza el Endpoint con ese fichero y sigue utilizando el Endpoint que venía en el fichero EasySII.xml si existe en el directorio y si no, lo envía siempre a Preproducción ya que es el Endpoint que tiene por defecto cuando no encuentra el fichero EasySII.xml.

Espero que nos podáis arrojar algo de luz.

Gracias.

**Comment by mdiago** [comment]
La declaración como campo estático de las urls de los endpoints provocaba que no se actualizarán los cambios realizados en el EndPointPrefix de la configuración. Se ha cambiado la definición de campo estático en la clase Wsd a propiedad estática, esto soluciona el problema. 
Gracias Fran por tu colaboración.
