### ISSUE TITLE
Error Contraseña de red

### ISSUE THREAD

**Issue by AiboAlcoi** [mdiago/EasySII#6]
Buenas tardes; desde hace unos meses estoy utilizando una aplicación para el envío de información a la A.E.A.T. y que desarrollé gracias a la implementación en la misma de su libreria EasySII. 
Hasta hoy utilizaba el fichero del tipo '.p12' para proceder a los envíos.
Hoy he recibido un fichero del tipo .pfx con la nueva firma digital emitido por la FNMT (el anterior caducaba en breve) y lo he instalado en el chrome, teniendo desde ahi un perfecto acceso a la página de la AEAT con todas sus funcionalidades.
Pero por otra parte, he procedido a modificar manualmente el número de serie, la huella digital, el path y la contarseña en el archivo EasySII.xml de configuración y cuando intento enviar facturas obtengo el error: 'la contraseña de red especificada no es válida'
¿podría alguien decirme qué estoy haciendo mal para conseguir el envío de facturas?
Muchas gracias por anticipado

**Comment by mdiago** [comment]
Prueba a eliminar del archivo de configuración los valores de 'CertificatePath' y de 'CertificatePassword'. El sistema intenta la carga del certificado según el siguiente orden:

1. Intenta la carga desde archivo de certificado si están incluidos los valores en la configuración: Parece que es este método el que te está dando problemas.
2. Intenta la carga del certificado del almacén de certificados de windows mediante la huella:
* En primer lugar en los certificado de usuario del usuario activo.
* En segundo lugar en los certificados almacenados en 'LocalMachine'.
3. Intenta la carga del certificado del almacén de certificados de windows mediante el número de serie:
* En primer lugar en los certificado de usuario del usuario activo.
* En segundo lugar en los certificados almacenados en 'LocalMachine'.

Borrando los datos 'CertificatePath' y de 'CertificatePassword' de la configuración haremos uso del almacén de certificados de windows (el que utiliza Chrome), y que no debería dar ningún problema.

**Comment by AiboAlcoi** [comment]
Muchas gracias por la respuesta.
El problema se ha resuelto aplicando tu información.
