### ISSUE TITLE
Error borrando bienes de inversión

### ISSUE THREAD

**Issue by jjcarles** [mdiago/EasySII#7]
Estoy haciendo pruebas con esta librería y tengo un caso que me está dando problemas. En concreto estoy intentando borrar un bien de inversión siguiendo el ejemplo de la wiki:
[https://github.com/mdiago/EasySII/wiki/011---Ejemplo:-Borrado-de-bienes-de-inversión.](https://github.com/mdiago/EasySII/wiki/011---Ejemplo:-Borrado-de-bienes-de-inversión.)

El problema está en el comando:
`BatchDispatcher.SendSiiLote(LoteBajaBienesInversion);`

Me he bajado el repositorio y lo he añadido a mi solución y la excepción
salta en el fichero `Batch.cs` en la función `GetEnvelope()`

Cuando ejecuta el comando `envelope.Body.GetType().GetProperty(GetSiiTypeName()).SetValue(envelope.Body,
siiInstance);`, en el caso de los bienes de inversión, el valor de `Body` es nulo.

Saludos.

**Comment by mdiago** [comment]
Muchas gracias por tu correo, gracias a él hemos detectado un bug en la calsse Asset.cs, en concreto en la línea 325, que hacía que fallara la funcionalidad de baja de bienes de inversión. 
Hemos solucionado el error y probado a realizar una baja sin problemas. Por favor, vuelve a probar con la versión actualizada de la biblioteca (1.0.2.1), y nos dices. Gracias.

**Comment by jjcarles** [comment]
Gracias por la rápida respuesta. Ahora si que ha funcionado.
Saludos.
