### ISSUE TITLE
Errores en la consultas de las facturas recibidas y facturas emitidas

### ISSUE THREAD

**Issue by jjcarles** [mdiago/EasySII#8]
Hola.

Tengo un par de errores(`System.NullReferenceException`) en las funciones `GetCustomerInvoices()` y `GetSupplierInvoices()` cuando ejecuto los ejemplos 015 y 016 de la wiki referente a la consulta de facturas recibidas y emitidas.

En el caso de la función `GetCustomerInvoices()`, el error salta en la linea 216 del fichero `QueryAeatExtern.cs`, en el `foreach`:

`foreach (var invoice in respuestasFE.RegistroRespuestaConsultaFactInformadasCliente)`

El valor de `RegistroRespuestaConsultaFactInformadasCliente` es nulo.

En el caso de la función `GetSupplierInvoices()`, el error salta en la linea 292 del mismo fichero `QueryAeatExtern.cs`, también en el `foreach`:

`foreach (var invoice in respuestaFR.RegistroRespuestaConsultaLRFactInformadasProveedor)`

El valor de `RegistroRespuestaConsultaLRFactInformadasProveedor` también es nulo.

Saludos.

**Comment by mdiago** [comment]
Solucionado el problema. Cuando el resultado de la consulta era "SinDatos" no controlabamos el null y daba el error.

**Comment by jjcarles** [comment]
Funciona sin problemas. Gracias.
