### ISSUE TITLE
Como enviar factura con 2 ivas y recargo de equivalencia

### ISSUE THREAD

**Issue by sysred7** [mdiago/EasySII#9]
Esta es la solución aportada por el equipo de Irene Soluctions.

Dim facturaEnviada As ARInvoice = New ARInvoice() ' Nueva factura
            facturaEnviada.IssueDate = New DateTime(F_Ano, F_Mes, F_Dia) ' Fecha factura
            facturaEnviada.SellerParty = emisor ' Emisor factura
            facturaEnviada.BuyerParty = New Party() ' Cliente
            facturaEnviada.BuyerParty.TaxIdentificationNumber = Trim(DataRows.Cells("CIF").Value())
            facturaEnviada.BuyerParty.PartyName = Trim(DataRows.Cells("Nombre").Value())
            facturaEnviada.CountryCode = Trim(DataRows.Cells("Pais").Value())
            facturaEnviada.InvoiceNumber = DataRows.Cells("Id").Value()
            facturaEnviada.InvoiceType = InvoiceType.F1 ' Factura normal
            facturaEnviada.ClaveRegimenEspecialOTrascendencia =
                ClaveRegimenEspecialOTrascendencia.RegimenComun ' Regimen común
            facturaEnviada.InvoiceText = DataRows.Cells("AEAT_Concepto").Value() ' Descripción
            facturaEnviada.GrossAmount = DataRows.Cells("Total").Value()  '' Importe bruto

           'Este proceso recupera los registros de iva pertenecientes a la factura
            SqlConnectionString(1) = CadenaConexion
            Using sqlConn As New SqlConnection(SqlConnectionString(1))
                Dim sqlda As New SqlDataAdapter
                Dim sqlcomm As New SqlCommand("PAM0001_ExportarAEAT_VtaIva", sqlConn)
                Dim ds As New DataSet
                Dim dr As Data.DataRow
                sqlcomm.CommandType = CommandType.StoredProcedure
                sqlcomm.Parameters.AddWithValue("Id", Trim(DataRows.Cells("Id").Value()))
                sqlda.SelectCommand = sqlcomm
                sqlConn.Open()
                sqlda.Fill(ds, "MiTabla")
                For Each dr In ds.Tables("MiTabla").Rows
                    If (dr("Recargo") = 0) Then
                        facturaEnviada.AddTaxOtuput(dr("Iva"), dr("BaseNeta"), dr("ImpIva"))
                    Else
                        facturaEnviada.AddTaxOtuput(dr("Recargo"), dr("BaseNeta"), dr("ImpIva"), dr("ImpRec"))   
                    End If
                Next
            End Using
 
            facturaEnviada.ToSII(True)
            Dim innerSII = facturaEnviada.InnerSII
            Dim fraExpedidaSII = innerSII.FacturaExpedida
            Dim desgloseIVA = fraExpedidaSII.TipoDesglose.DesgloseFactura.Sujeta.NoExenta.DesgloseIVA
            For Each detalleIVA In desgloseIVA.DetalleIVA
               If (nz(detalleIVA.TipoRecargoEquivalencia, "") <> "") Then
                  Dim taxAmount = SIIParser.ToDecimal(detalleIVA.CuotaRepercutida)
                        Dim taxBase = SIIParser.ToDecimal(detalleIVA.BaseImponible)
                  Dim taxRate = Math.Round(taxAmount * 100 / taxBase, 1)
                  detalleIVA.TipoImpositivo = SIIParser.FromDecimal(taxRate)
               End If
            Next
 
            LoteDeFacturasEmitidas.BatchItems.Add(facturaEnviada) ' Añadimos la nueva factura al lote

Muchas gracias al equipo de Irene Solutions, por la aportación para aclarar este tipo de envio.

**Comment by mdiago** [comment]
Gracias a ti por el feedback! ;-)
